### ISSUE TITLE
Python 2.x support?

### ISSUE THREAD

**Issue by gosella** [gosella/autopython#4]
Currently, AutoPython (and AutoIPython) only supports Python 3.x.

Is there any interest on supporting Python 2.x also?

**Comment by juanrodriguezmonti** [comment]
I guess that Python 2 is a double edged sword. Because, for example, my Ubuntu comes with Python 2.x, and other distributions, too. So, it's useful. But, on the other hand, Python 2 is gonna die.

I guess that a good idea is to indicate at the moment of the install with pip and Python 2, is that Autopython only supports Python 3.x, trying to avoid that nasty error message.

Thanks!

**Comment by gosella** [comment]
As Guido recently remind us (https://www.youtube.com/watch?v=YgtL4S7Hrwo), Python 2.7 will be around until 2020... (just look at https://pythonclock.org/ !!!)

So, I bite the bullet and now we also have AutoPython for Python 2.7 :smiley: 

Probably there are some Unicode related bugs lying around in the code (it's the same code base for Python 2.x and 3.x) but as far as I can tell, it is working properly.
